version: '3.7'

services:
    db:
        image: postgres:11
        container_name: goproj_db
        ports:
            - 32705:5432
        # volumes:
        #     - ./db_data:/var/lib/postgresql/db_data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: goproj

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
          PGADMIN_DEFAULT_EMAIL: user@example.com
          PGADMIN_DEFAULT_PASSWORD: password
        depends_on:
          - db
        ports:
          - "5050:80"
        restart: unless-stopped
